In [8]:
import pandas
import numpy
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plot
import os
import numpy as np
import cv2
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import matplotlib.pyplot as plt 


In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
data_url = '/content/drive/MyDrive/Dataset'
categories = ["0","1","2","3","4","5","6","7","8","9"]
dataset = []
out = []
# store and normalize data 
for cat in categories :
    path = os.path.join(data_url,cat)
    for imgPath in os.listdir(path):
        image = cv2.imread(os.path.join(path,imgPath),cv2.IMREAD_GRAYSCALE)
        image = cv2.resize(image, (64,64))
        image = image.astype('float32')
        image /= 255
        dataset.append(image)
        out.append(categories.index(cat))
        #plt.imshow(image,cmap="gray")
        #plt.show()
        


In [11]:
x_train, x_test, y_train, y_test = train_test_split(dataset, out, test_size=0.2, random_state=42)



x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

x_test = np.asarray(x_test)
y_test = np.asarray(y_test)



x_train = np.reshape(x_train,(len(x_train),64*64))
x_test = np.reshape(x_test,(len(x_test),64*64))



In [12]:
model = SVC() #kernel='linear'
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.8038740920096852


In [14]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(classification_report(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.93      0.91        40
           1       0.83      0.92      0.87        48
           2       0.86      0.72      0.78        50
           3       0.87      0.74      0.80        35
           4       0.59      0.69      0.64        32
           5       0.86      0.84      0.85        38
           6       0.72      0.76      0.74        41
           7       0.69      0.76      0.72        38
           8       0.82      0.80      0.81        45
           9       0.89      0.85      0.87        46

    accuracy                           0.80       413
   macro avg       0.80      0.80      0.80       413
weighted avg       0.81      0.80      0.80       413

[[37  1  0  0  0  0  0  1  0  1]
 [ 0 44  0  0  0  0  1  1  2  0]
 [ 1  4 36  2  0  0  3  4  0  0]
 [ 0  1  3 26  0  5  0  0  0  0]
 [ 0  0  0  0 22  0  6  4  0  0]
 [ 0  0  0  2  4 32  0  0  0  0]
 [ 0  0  2  0  4  0 31  1  1  2]
 [ 1  1  1